--------------------------------------------------------
--  File created - Tuesday-March-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHARACTERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CHARACTERS" 
   (	"ID" NUMBER(*,0), 
	"FILM_ID" NUMBER(*,0), 
	"FILM" VARCHAR2(128 BYTE), 
	"CHARACTER_ID" NUMBER(*,0), 
	"CHARACTERS" VARCHAR2(128 BYTE), 
	"ACTOR" VARCHAR2(26 BYTE), 
	"PHASE_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CHARACTERS
SET DEFINE OFF;
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (1,1,'Iron Man',1,'Tony Stark/Iron Man','Robert Downey ,Jr.',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (2,1,'Iron Man',2,'Rhodey','Terrence Howard',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (3,1,'Iron Man',3,'Obadiah Stane','Jeff Bridges',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (4,1,'Iron Man',4,'Virginia "Pepper" Potts','Gwyneth Paltrow',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (5,2,'The Incredible Hulk',5,'Bruce Banner','Edward Norton',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (6,3,'Iron Man 2',1,'Tony Stark','Robert Downey, Jr.',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (7,3,'Iron Man 2',4,'Pepper Potts','Gwyneth Paltrow',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (8,3,'Iron Man 2',8,'Natalie Rushman/Natasha Romanoff','Scarlett Johansson',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (9,3,'Iron Man 2',9,'Lt. Col. James "Rhodey" Rhodes','Don Cheadle',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (10,3,'Iron Man 2',10,'Ivan Vanko','Mickey Rourke',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (11,4,'Thor',11,'Thor','Chris Hemsworth',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (12,4,'Thor',12,'Jane Foster','Natalie Portman',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (13,4,'Thor',13,'Loki','Tom Hiddleston',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (14,4,'Thor',14,'Odin','Anthony Hopkins',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (15,4,'Thor',15,'Heimdall','Idris Elba',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (16,5,'Captain America: The First Avenger',16,'Steve Rogers / Captain America','Chris Evans',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (17,5,'Captain America: The First Avenger',17,'Chester Philips','Tommy Lee Jones',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (18,5,'Captain America: The First Avenger',18,'Bucky Barnes','Sebastian Stan',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (19,5,'Captain America: The First Avenger',19,'Peggy Carter','Hayley Atwell',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (20,6,'The Avengers',13,'Loki','Tom Hiddleston',1);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (21,7,'Iron Man 3',1,'Tony Stark/Iron Man','Robert Downey, Jr.',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (22,7,'Iron Man 3',4,'Pepper Potts','Gwyneth Paltrow',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (23,7,'Iron Man 3',9,'James ''Rhodey'' Rhodes','Don Cheadle',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (24,7,'Iron Man 3',24,'Aldrich Killian','Guy Pearce',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (25,7,'Iron Man 3',25,'The Mandarin','Ben Kingsley',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (26,8,'Thor: The Dark World',11,'Thor','Chris Hemsworth',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (27,8,'Thor: The Dark World',12,'Jane Foster','Natalie Portman',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (28,8,'Thor: The Dark World',13,'Loki','Tom Hiddleston',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (29,8,'Thor: The Dark World',14,'Odin','Anthony Hopkins',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (30,8,'Thor: The Dark World',15,'Heimdall','Idris Elba',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (31,8,'Thor: The Dark World',31,'Malekith the Accursed','Christopher Eccleston',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (32,8,'Thor: The Dark World',32,'Sif','Jaimie Alexander',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (33,9,'Captain America: The Winter Soldier',16,'Captain America/Steve Rogers','Chris Evans',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (34,9,'Captain America: The Winter Soldier',8,'Natasha Romanoff/Black Widow','Scarlett Johansson',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (35,9,'Captain America: The Winter Soldier',18,'Bucky Barnes/Winter Soldier','Sebastian Stan',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (36,9,'Captain America: The Winter Soldier',36,'Agent Alexander Pierce','Robert Redford',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (37,9,'Captain America: The Winter Soldier',37,'Nick Fury','Samuel L. Jackson',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (38,10,'Guardians of the Galaxy',38,'Peter Quill','Chris Pratt',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (39,10,'Guardians of the Galaxy',39,'Gamora','Zoe Saldana',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (40,10,'Guardians of the Galaxy',40,'Drax','Dave Bautista',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (41,10,'Guardians of the Galaxy',41,'Groot','Vin Diesel',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (42,10,'Guardians of the Galaxy',42,'Rocket','Bradley Cooper',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (43,11,'Avengers: Age of Ultron',43,'Ultron','James Spader',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (44,12,'Ant-Man',44,'Scott Lang / Ant-Man','Paul Rudd',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (45,12,'Ant-Man',45,'Hope Van Dyne','Evangeline Lilly',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (46,12,'Ant-Man',46,'Darren Cross / Yellowjacket','Corey Stoll',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (47,12,'Ant-Man',47,'Paxton','Bobby Cannavale',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (48,12,'Ant-Man',48,'Luis','Michael Pe�a',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (49,12,'Ant-Man',49,'Dr Hank Pym / Ant-Man','Michael Douglas',2);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (50,13,'Captain America: Civil War',16,'Steve Rogers/Captain America','Chris Evans',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (51,13,'Captain America: Civil War',1,'Tony Stark/Iron Man','Robert Downey, Jr.',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (52,13,'Captain America: Civil War',8,'Natasha Romanoff / Black Widow','Scarlett Johansson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (53,13,'Captain America: Civil War',18,'Bucky Barnes/Winter Soldier','Sebastian Stan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (54,13,'Captain America: Civil War',54,'Clint Barton/Hawkeye','Jeremy Renner',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (55,13,'Captain America: Civil War',9,'James Rhodes/War Machine','Don Cheadle',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (56,13,'Captain America: Civil War',56,'Sam Wilson/Falcon','Anthony Mackie',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (57,13,'Captain America: Civil War',57,'Vision','Paul Bettany',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (58,13,'Captain America: Civil War',58,'Wanda Maximoff/Scarlet Witch','Elizabeth Olsen',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (59,13,'Captain America: Civil War',59,'T''Challa/Black Panther','Chadwick Boseman',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (60,14,'Doctor Strange',60,'Doctor Stephen Strange','Benedict Cumberbatch',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (61,14,'Doctor Strange',61,'Baron Mordo','Chiwetel Ejiofor',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (62,14,'Doctor Strange',62,'Dr. Christine Palmer','Rachel McAdams',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (63,14,'Doctor Strange',63,'Master Wong','Benedict Wong',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (64,14,'Doctor Strange',64,'Kaecilius','Mads Mikkelsen',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (65,14,'Doctor Strange',65,'The Ancient One','Tilda Swinton',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (66,15,'Guardians of the Galaxy Vol. 2',38,'Peter Quill/Star-Lord','Chris Pratt',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (67,15,'Guardians of the Galaxy Vol. 2',39,'Gamora','Zoe Saldana',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (68,15,'Guardians of the Galaxy Vol. 2',40,'Drax the Destroyer','Dave Bautista',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (69,15,'Guardians of the Galaxy Vol. 2',41,'Baby Groot','Vin Diesel',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (70,15,'Guardians of the Galaxy Vol. 2',42,'Rocket','Bradley Cooper',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (71,15,'Guardians of the Galaxy Vol. 2',71,'Yondu Udonta','Michael Rooker',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (72,15,'Guardians of the Galaxy Vol. 2',72,'Ego','Kurt Russell',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (73,15,'Guardians of the Galaxy Vol. 2',73,'Nebula','Karen Gillan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (74,15,'Guardians of the Galaxy Vol. 2',74,'Mantis','Pom Klementieff',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (75,15,'Guardians of the Galaxy Vol. 2',75,'Ayesha','Elizabeth Debicki',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (76,16,'Spider-Man: Homecoming',76,'Peter Parker / Spider-Man','Tom Holland',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (77,16,'Spider-Man: Homecoming',77,'Adrian Toomes/Vulture','Michael Keaton',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (78,16,'Spider-Man: Homecoming',78,'Michelle','Zendaya',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (79,16,'Spider-Man: Homecoming',79,'Happy Hogan','Jon Favreau',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (80,16,'Spider-Man: Homecoming',80,'Aunt May','Marisa Tomei',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (81,16,'Spider-Man: Homecoming',1,'Tony Stark/Iron Man','Robert Downey, Jr.',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (82,17,'Thor: Ragnarok',11,'Thor','Chris Hemsworth',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (83,17,'Thor: Ragnarok',13,'Loki','Tom Hiddleston',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (84,17,'Thor: Ragnarok',84,'Hela','Cate Blanchett',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (85,17,'Thor: Ragnarok',15,'Heimdall','Idris Elba',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (86,17,'Thor: Ragnarok',86,'Grandmaster','Jeff Goldblum',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (87,17,'Thor: Ragnarok',87,'Valkyrie','Tessa Thompson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (88,17,'Thor: Ragnarok',88,'Skurge','Karl Urban',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (89,17,'Thor: Ragnarok',89,'Bruce Banner/Hulk','Mark Ruffalo',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (90,17,'Thor: Ragnarok',14,'Odin','Anthony Hopkins',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (91,18,'Black Panther',59,'T�Challa/Black Panther','Chadwick Boseman',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (92,18,'Black Panther',92,'Erik Killmonger','Michael B. Jordan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (93,18,'Black Panther',93,'Nakia','Lupita Nyong''o',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (94,18,'Black Panther',94,'Okoye','Danai Gurira',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (95,18,'Black Panther',95,'Everett K. Ross','Martin Freeman',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (96,18,'Black Panther',96,'Ramonda','Angela Bassett',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (97,18,'Black Panther',97,'Zuri','Forest Whitaker',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (98,18,'Black Panther',98,'Ulysses Klaue','Andy Serkis',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (99,18,'Black Panther',99,'W�Kabi','Daniel Kaluuya',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (100,18,'Black Panther',100,'Shuri','Letitia Wright',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (101,19,'Avengers: Infinity Warr',1,'Tony Stark/Iron Man','Robert Downey, Jr.',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (102,19,'Avengers: Infinity Warr',11,'Thor','Chris Hemsworth',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (103,19,'Avengers: Infinity Warr',89,'Bruce Banner/Hulk','Mark Ruffalo',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (104,19,'Avengers: Infinity Warr',16,'Steve Rogers','Chris Evans',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (105,19,'Avengers: Infinity Warr',8,'Natasha Romanoff/Black Widow','Scarlett Johansson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (106,19,'Avengers: Infinity Warr',60,'Stephen Strange','Benedict Cumberbatch',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (107,19,'Avengers: Infinity Warr',9,'James Rhodes / War Machine','Don Cheadle',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (108,19,'Avengers: Infinity Warr',76,'Peter Parker/Spider-Man','Tom Holland',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (109,19,'Avengers: Infinity Warr',59,'T''Challa / Black Panther','Chadwick Boseman',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (110,19,'Avengers: Infinity Warr',57,'Vision','Paul Bettany',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (111,19,'Avengers: Infinity Warr',58,'Wanda Maximoff/Scarlet Witch','Elizabeth Olsen',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (112,19,'Avengers: Infinity Warr',18,'Bucky Barnes/Winter Soldier','Sebastian Stan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (113,19,'Avengers: Infinity Warr',94,'Okoye','Danai Gurira',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (114,19,'Avengers: Infinity Warr',100,'Shuri','Letitia Wright',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (115,19,'Avengers: Infinity Warr',40,'Drax the Destroyer','Dave Bautista',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (116,19,'Avengers: Infinity Warr',39,'Gamora','Zoe Saldana',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (117,19,'Avengers: Infinity Warr',117,'Thanos','Josh Brolin',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (118,19,'Avengers: Infinity Warr',38,'Peter Quill/Star-Lord','Chris Pratt',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (119,19,'Avengers: Infinity Warr',63,'Wong','Benedict Wong',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (120,19,'Avengers: Infinity Warr',74,'Mantis','Pom Klementieff',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (121,19,'Avengers: Infinity Warr',73,'Nebula','Karen Gillan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (122,19,'Avengers: Infinity Warr',41,'Groot','Vin Diesel',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (123,19,'Avengers: Infinity Warr',42,'Rocket Raccoon','Bradley Cooper',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (124,20,'Ant-Man and the Wasp',44,'Scott Lang/Ant-Man','Paul Rudd',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (125,20,'Ant-Man and the Wasp',45,'Hope van Dyne/The Wasp','Evangeline Lilly',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (126,20,'Ant-Man and the Wasp',48,'Luis','Michael Pe�a',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (127,20,'Ant-Man and the Wasp',127,'Sonny Burch','Walton Goggins',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (128,20,'Ant-Man and the Wasp',128,'Ava Starr/Ghost','Hannah John-Kamen',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (129,20,'Ant-Man and the Wasp',129,'Janet van Dyne','Michelle Pfeiffer',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (130,20,'Ant-Man and the Wasp',130,'Dr. Bill Foster/Goliath','Laurence Fishburne',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (131,20,'Ant-Man and the Wasp',49,'Dr. Hank Pym','Michael Douglas',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (132,21,'Captain Marvel',132,'Carol Danvers/Vers/Captain Marvel','Brie Larson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (133,21,'Captain Marvel',37,'Nick Fury','Samuel L. Jackson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (134,21,'Captain Marvel',134,'Talos/Keller','Ben Mendelsohn',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (135,21,'Captain Marvel',135,'Korath the Pursuer','Djimon Hounsou',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (136,21,'Captain Marvel',136,'Ronan the Accuser','Lee Pace',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (137,21,'Captain Marvel',137,'Maria Rambeau','Lashana Lynch',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (138,21,'Captain Marvel',138,'Minn-Erva','Gemma Chan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (139,21,'Captain Marvel',139,'Supreme Intelligence','Annette Bening',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (140,21,'Captain Marvel',140,'Agent Phil Coulson','Clark Gregg',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (141,22,'Avengers: Endgame',1,'Tony Stark/Iron Man','Robert Downey, Jr.',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (142,22,'Avengers: Endgame',16,'Steve Rogers/Captain America','Chris Evans',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (143,22,'Avengers: Endgame',89,'Bruce Banner/Hulk','Mark Ruffalo',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (144,22,'Avengers: Endgame',11,'Thor','Chris Hemsworth',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (145,22,'Avengers: Endgame',8,'Natasha Romanoff/Black Widow','Scarlett Johansson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (146,22,'Avengers: Endgame',146,'Clint Barton/Hawkeye','Jeremy Renner',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (147,22,'Avengers: Endgame',9,'James �Rhodey� Rhodes/War Machine','Don Cheadle',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (148,22,'Avengers: Endgame',44,'Scott Lang/Ant-Man','Paul Rudd',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (149,22,'Avengers: Endgame',132,'Carol Danvers/Captain Marvel','Brie Larson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (150,22,'Avengers: Endgame',73,'Nebula','Karen Gillan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (151,22,'Avengers: Endgame',94,'Okoye','Danai Gurira',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (152,22,'Avengers: Endgame',42,'Rocket','Bradley Cooper',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (153,22,'Avengers: Endgame',117,'Thanos','Josh Brolin',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (154,22,'Avengers: Endgame',63,'Wong','Benedict Wong',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (155,22,'Avengers: Endgame',79,'Happy Hogan','Jon Favreau',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (156,22,'Avengers: Endgame',4,'Pepper Potts','Gwyneth Paltrow',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (157,22,'Avengers: Endgame',45,'Hope van Dyne/The Wasp','Evangeline Lilly',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (158,22,'Avengers: Endgame',60,'Dr. Stephen Strange','Benedict Cumberbatch',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (159,22,'Avengers: Endgame',76,'Peter Parker/Spider-Man','Tom Holland',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (160,22,'Avengers: Endgame',38,'Peter Quill/Star-Lord','Chris Pratt',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (161,22,'Avengers: Endgame',40,'Drax the Destroyer','Dave Bautista',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (162,22,'Avengers: Endgame',18,'Bucky Barnes/Winter Soldier','Sebastian Stan',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (163,22,'Avengers: Endgame',163,'Groot','Terry Notary',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (164,22,'Avengers: Endgame',56,'Sam Wilson/Falcon','Anthony Mackie',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (165,22,'Avengers: Endgame',13,'Loki','Tom Hiddleston',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (166,22,'Avengers: Endgame',100,'Shuri','Letitia Wright',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (167,22,'Avengers: Endgame',37,'Nick Fury','Samuel L. Jackson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (168,22,'Avengers: Endgame',74,'Mantis','Pom Klementieff',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (169,22,'Avengers: Endgame',57,'Vision','Paul Bettany',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (170,22,'Avengers: Endgame',58,'Wanda Maximoff/Scarlet Witch','Elizabeth Olsen',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (171,22,'Avengers: Endgame',39,'Gamora','Zoe Saldana',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (172,22,'Avengers: Endgame',59,'T�Challa/Black Panther','Chadwick Boseman',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (173,23,'Spider-Man: Far From Home',76,'Peter Parker/Spider-Man','Tom Holland',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (174,23,'Spider-Man: Far From Home',37,'Nick Fury','Samuel L. Jackson',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (175,23,'Spider-Man: Far From Home',78,'Michelle �MJ� Jones','Zendaya',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (176,23,'Spider-Man: Far From Home',176,'Quentin Beck/Mysterio','Jake Gyllenhaal',3);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (177,24,'Black Widow',8,'Natasha Romanoff/Black Widow','Scarlett Johansson',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (178,24,'Black Widow',178,'Yelena Belova','Florence Pugh',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (179,24,'Black Widow',179,'Melina','Rachel Weisz',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (180,24,'Black Widow',180,'Alexei/Red Guardian','David Harbour',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (181,24,'Black Widow',181,'Dreykov','Ray Winstone',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (182,24,'Black Widow',182,'Mason','O.T. Fagbenle',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (183,25,'Shang-Chi and the Legend of the Ten Rings',183,'Shang-Chi','Simu Liu',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (184,26,'Eternals',184,'Kingo','Kumail Nanjiani',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (185,26,'Eternals',185,'Thena','Angelina Jolie',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (186,26,'Eternals',186,'Ikaris','Richard Madden',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (187,26,'Eternals',187,'Ajak','Salma Hayek',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (188,26,'Eternals',188,'Phastos','Brian Tyree Henry',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (189,26,'Eternals',189,'Makkari','Lauren Ridloff',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (190,26,'Eternals',190,'Druig','Barry Keoghan',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (191,26,'Eternals',138,'Sersi','Gemma Chan',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (192,26,'Eternals',192,'Sprite','Lia McHugh',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (193,26,'Eternals',193,'Gilgamesh','Don Lee',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (194,27,'Spider-Man: No Way Home',76,'Peter Parker/Spider-Man','Tom Holland',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (195,28,'Doctor Strange in the Multiverse of Madness',60,'Dr. Stephen Strange','Benedict Cumberbatch',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (196,28,'Doctor Strange in the Multiverse of Madness',58,'Scarlett Witch','Elizabeth Olsen',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (197,28,'Doctor Strange in the Multiverse of Madness',61,'Karl Mordo','Chiwetel Ejiofor',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (198,28,'Doctor Strange in the Multiverse of Madness',63,'Wong','Benedict Wong',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (199,28,'Doctor Strange in the Multiverse of Madness',199,'America Chavez','Xochitl Gomez',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (200,28,'Doctor Strange in the Multiverse of Madness',200,'Nicodemus West','Michael Stuhlbarg',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (201,28,'Doctor Strange in the Multiverse of Madness',62,'Dr. Christine Palmer','Rachel McAdams',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (202,29,'Thor: Love and Thunder',11,'Thor','Chris Hemsworth',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (203,29,'Thor: Love and Thunder',203,'Gorr the God Butcher','Christian Bale',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (204,29,'Thor: Love and Thunder',87,'King Valkyrie','Tessa Thompson',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (205,29,'Thor: Love and Thunder',205,'Korg','Taika Waititi',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (206,29,'Thor: Love and Thunder',206,'Zeus','Russell Crowe',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (207,29,'Thor: Love and Thunder',12,'Jane Foster/Mighty Thor','Natalie Portman',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (208,30,'Black Panther: Wakanda Forever',100,'Shuri','Letitia Wright',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (209,30,'Black Panther: Wakanda Forever',93,'Nakia','Lupita Nyong''o',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (210,30,'Black Panther: Wakanda Forever',94,'Okoye','Danai Gurira',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (211,30,'Black Panther: Wakanda Forever',211,'M�Baku','Winston Duke',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (212,30,'Black Panther: Wakanda Forever',212,'Riri Williams/Ironheart','Dominique Thorne',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (213,30,'Black Panther: Wakanda Forever',213,'Ayo','Florence Kasumba',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (214,30,'Black Panther: Wakanda Forever',214,'Aneka','Michaela Coel',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (215,30,'Black Panther: Wakanda Forever',215,'Namor','Tenoch Huerta',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (216,30,'Black Panther: Wakanda Forever',95,'Everett K. Ross','Martin Freeman',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (217,30,'Black Panther: Wakanda Forever',96,'Ramonda','Angela Bassett',4);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (218,31,'Ant-Man and the Wasp: Quantumania',44,'Scott Lang / Ant-Man','Paul Rudd',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (219,31,'Ant-Man and the Wasp: Quantumania',45,'Hope van Dyne / Wasp','Evangeline Lilly',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (220,31,'Ant-Man and the Wasp: Quantumania',220,'Kang the Conqueror','Jonathan Majors',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (221,31,'Ant-Man and the Wasp: Quantumania',221,'Cassie Lang','Kathryn Newton',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (222,31,'Ant-Man and the Wasp: Quantumania',222,'Lord Krylar','Bill Murray',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (223,31,'Ant-Man and the Wasp: Quantumania',129,'Janet van Dyne','Michelle Pfeiffer',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (224,31,'Ant-Man and the Wasp: Quantumania',49,'Dr. Hank Pym','Michael Douglas',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (225,32,'Guardians of the Galaxy Vol. 3',38,'Peter Quill / Star-Lord','Chris Pratt',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (226,32,'Guardians of the Galaxy Vol. 3',39,'Gamora','Zoe Saldana',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (227,32,'Guardians of the Galaxy Vol. 3',40,'Drax the Destroyer','Dave Bautista',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (228,32,'Guardians of the Galaxy Vol. 3',73,'Nebula','Karen Gillan',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (229,32,'Guardians of the Galaxy Vol. 3',74,'Mantis','Pom Klementieff',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (230,32,'Guardians of the Galaxy Vol. 3',41,'Groot','Vin Diesel',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (231,32,'Guardians of the Galaxy Vol. 3',42,'Rocket','Bradley Cooper',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (232,32,'Guardians of the Galaxy Vol. 3',232,'Kraglin Obfonteri/Young Rocket/Lamb-Shank','Sean Gunn',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (233,32,'Guardians of the Galaxy Vol. 3',233,'Cosmo the Spacedog','Maria Bakalova',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (234,33,'The Marvels',132,'Carol Danvers / Captain Marvel','Brie Larson',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (235,33,'The Marvels',235,'Monica Rambeau','Teyonah Parris',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (236,33,'The Marvels',37,'Nick Fury','Samuel L. Jackson',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (237,33,'The Marvels',237,'Kamala Khan / Ms. Marvel','Iman Vellani',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (238,34,'Deadpool & Wolverine',238,'Wade Wilson / Deadpool','Ryan Reynolds',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (239,34,'Deadpool & Wolverine',239,'James �Logan� Howlett / Wolverine','Hugh Jackman',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (240,35,'Captain America: Brave New World',56,'Sam Wilson / Captain America','Anthony Mackie',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (241,35,'Captain America: Brave New World',241,'Joaquin Torres / Falcon','Danny Ramirez',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (242,35,'Captain America: Brave New World',242,'Ruth Bat-Seraph','Shira Haas',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (243,35,'Captain America: Brave New World',243,'Sidewinder','Giancarlo Esposito',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (244,35,'Captain America: Brave New World',244,'Samuel Sterns / Leader','Tim Blake Nelson',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (245,35,'Captain America: Brave New World',245,'President Thaddeus �Thunderbolt� Ross','Harrison Ford',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (246,36,'Thunderbolts',178,'Yelena Belova','Florence Pugh',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (247,36,'Thunderbolts',18,'Bucky Barnes','Sebastian Stan',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (248,36,'Thunderbolts',180,'Alexei Shostakov','David Harbour',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (249,36,'Thunderbolts',249,'Antonia Dreykov','Olga Kurylenko',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (250,36,'Thunderbolts',250,'John Walker','Wyatt Russell',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (251,36,'Thunderbolts',128,'Ava Starr','Hannah John-Kamen',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (252,36,'Thunderbolts',252,'Bob','Lewis James Pullman',5);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (253,37,'The Fantastic Four: First Steps',253,'Reed Richards/Mister Fantastic','Pedro Pascal',6);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (254,37,'The Fantastic Four: First Steps',254,'Sue Storm/Invisible Woman','Vanessa Kirby',6);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (255,37,'The Fantastic Four: First Steps',255,'Johnny Storm/Human Torch','Joseph Quinn',6);
Insert into SYSTEM.CHARACTERS (ID,FILM_ID,FILM,CHARACTER_ID,CHARACTERS,ACTOR,PHASE_ID) values (256,37,'The Fantastic Four: First Steps',256,'Ben Grimm/The Thing','Ebon Moss-Bachrach',6);
